# Generated by Django 4.0.1 on 2022-02-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_ocultar'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ocultar',
            field=models.BooleanField(default=False),
        ),
    ]
